import { useEffect, useState } from 'react'
import { formatDate } from '../lib/data'

const statusOptions = ['Documented','Inspector Confirmed','Customer Reported','AI Inferred','Unknown']
const emptyDNA = {
  lifecycle_status:'Active', record_mode:'Legacy / Existing', construction_material:'', capacity:'', design_pressure:'', design_temperature:'', service_environment:'',
  original_coating_family:'', original_coating_manufacturer:'', original_coating_product:'', original_coating_date:'', original_dft:'', original_surface_prep:'',
  current_coating_family:'', current_coating_manufacturer:'', current_coating_product:'', current_coating_date:'', current_dft:'', current_surface_prep:'',
  coating_record_status:'Unknown', construction_record_status:'Unknown', baseline_date:'', baseline_notes:''
}
const emptyEvent = { event_date:new Date().toISOString().slice(0,10), event_type:'Repair', area:'', defect_found:'', coating_family:'', manufacturer:'', product_name:'', surface_prep:'', dft:'', contractor:'', source_status:'Documented', establishes_baseline:false, notes:'' }

function Field({label, children}) { return <label>{label}{children}</label> }
function Value({label, value}) { return <div><dt>{label}</dt><dd>{value || 'Unknown / not documented'}</dd></div> }

export default function AssetDNA({ asset, dna, events = [], onSaveDNA, onAddEvent }) {
  const [editing,setEditing]=useState(false), [adding,setAdding]=useState(false), [busy,setBusy]=useState(false), [error,setError]=useState('')
  const [form,setForm]=useState({...emptyDNA,...(dna||{})}), [event,setEvent]=useState(emptyEvent)
  useEffect(()=>setForm({...emptyDNA,...(dna||{})}),[dna])
  const change=(key,value)=>setForm(v=>({...v,[key]:value})), eventChange=(key,value)=>setEvent(v=>({...v,[key]:value}))
  const save=async()=>{setBusy(true);setError('');try{await onSaveDNA(form);setEditing(false)}catch(e){setError(e.message||'Could not save Asset DNA.')}finally{setBusy(false)}}
  const add=async()=>{setBusy(true);setError('');try{await onAddEvent(event);setEvent({...emptyEvent,event_date:new Date().toISOString().slice(0,10)});setAdding(false)}catch(e){setError(e.message||'Could not save service event.')}finally{setBusy(false)}}
  const latestBaseline=events.find(x=>x.establishes_baseline)
  return <section className="panel asset-dna-panel">
    <div className="section-header"><div><p className="eyebrow">Asset intelligence</p><h2>Asset DNA</h2><p className="muted">Legacy information may remain unknown. Verified repairs and rehabilitations build the trusted baseline from this point forward.</p></div><div className="section-actions"><button className="secondary-button" onClick={()=>setAdding(!adding)}>＋ Service event</button><button className="primary-button" onClick={()=>setEditing(!editing)}>{editing?'Cancel edit':'Edit DNA'}</button></div></div>
    <div className="dna-trust-strip"><span><small>Lifecycle</small><strong>{form.lifecycle_status || 'Active'}</strong></span><span><small>Record mode</small><strong>{form.record_mode}</strong></span><span><small>Construction source</small><strong>{form.construction_record_status}</strong></span><span><small>Coating source</small><strong>{form.coating_record_status}</strong></span><span><small>Known baseline</small><strong>{latestBaseline?formatDate(latestBaseline.event_date):(form.baseline_date?formatDate(form.baseline_date):'Not established')}</strong></span></div>
    {error&&<div className="error-message">{error}</div>}
    {editing ? <div className="form-stack dna-editor">
      <div className="form-grid"><Field label="Record mode"><select value={form.record_mode} onChange={e=>change('record_mode',e.target.value)}><option>Legacy / Existing</option><option>Known / New</option><option>Rehabilitated Baseline</option></select></Field><Field label="Construction source"><select value={form.construction_record_status} onChange={e=>change('construction_record_status',e.target.value)}>{statusOptions.map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Construction material"><input value={form.construction_material||''} onChange={e=>change('construction_material',e.target.value)} placeholder="Unknown is OK"/></Field><Field label="Capacity"><input value={form.capacity||''} onChange={e=>change('capacity',e.target.value)} placeholder="e.g. 20,000 gal"/></Field><Field label="Design pressure"><input value={form.design_pressure||''} onChange={e=>change('design_pressure',e.target.value)}/></Field><Field label="Design temperature"><input value={form.design_temperature||''} onChange={e=>change('design_temperature',e.target.value)}/></Field><Field label="Service environment"><input value={form.service_environment||''} onChange={e=>change('service_environment',e.target.value)} placeholder="Potable water, wastewater, hot water…"/></Field><Field label="Coating information source"><select value={form.coating_record_status} onChange={e=>change('coating_record_status',e.target.value)}>{statusOptions.map(x=><option key={x}>{x}</option>)}</select></Field></div>
      <h3>Original / earliest known coating</h3><div className="form-grid"><Field label="Family"><input value={form.original_coating_family||''} onChange={e=>change('original_coating_family',e.target.value)} placeholder="Unknown is OK"/></Field><Field label="Manufacturer"><input value={form.original_coating_manufacturer||''} onChange={e=>change('original_coating_manufacturer',e.target.value)}/></Field><Field label="Product"><input value={form.original_coating_product||''} onChange={e=>change('original_coating_product',e.target.value)}/></Field><Field label="Applied date"><input type="date" value={form.original_coating_date||''} onChange={e=>change('original_coating_date',e.target.value)}/></Field><Field label="DFT"><input value={form.original_dft||''} onChange={e=>change('original_dft',e.target.value)}/></Field><Field label="Surface preparation"><input value={form.original_surface_prep||''} onChange={e=>change('original_surface_prep',e.target.value)}/></Field></div>
      <h3>Current documented system</h3><div className="form-grid"><Field label="Family"><input value={form.current_coating_family||''} onChange={e=>change('current_coating_family',e.target.value)}/></Field><Field label="Manufacturer"><input value={form.current_coating_manufacturer||''} onChange={e=>change('current_coating_manufacturer',e.target.value)}/></Field><Field label="Product"><input value={form.current_coating_product||''} onChange={e=>change('current_coating_product',e.target.value)}/></Field><Field label="Applied / rehab date"><input type="date" value={form.current_coating_date||''} onChange={e=>change('current_coating_date',e.target.value)}/></Field><Field label="DFT"><input value={form.current_dft||''} onChange={e=>change('current_dft',e.target.value)}/></Field><Field label="Surface preparation"><input value={form.current_surface_prep||''} onChange={e=>change('current_surface_prep',e.target.value)}/></Field></div>
      <Field label="Baseline notes"><textarea rows="3" value={form.baseline_notes||''} onChange={e=>change('baseline_notes',e.target.value)} placeholder="Record what is known, what is unknown, and where the information came from."/></Field><button className="primary-button" disabled={busy} onClick={save}>{busy?'Saving…':'Save Asset DNA'}</button>
    </div> : <><div className="dna-columns"><dl className="detail-list"><Value label="Construction" value={form.construction_material}/><Value label="Capacity" value={form.capacity}/><Value label="Service" value={form.service_environment}/><Value label="Original coating" value={[form.original_coating_manufacturer,form.original_coating_product||form.original_coating_family].filter(Boolean).join(' · ')}/></dl><dl className="detail-list"><Value label="Current coating" value={[form.current_coating_manufacturer,form.current_coating_product||form.current_coating_family].filter(Boolean).join(' · ')}/><Value label="Current DFT" value={form.current_dft}/><Value label="Current surface prep" value={form.current_surface_prep}/><Value label="Baseline notes" value={form.baseline_notes}/></dl></div></>}
    {adding&&<div className="dna-event-form"><h3>Add repair / rehabilitation / service event</h3><div className="form-grid"><Field label="Date"><input type="date" value={event.event_date} onChange={e=>eventChange('event_date',e.target.value)}/></Field><Field label="Event type"><select value={event.event_type} onChange={e=>eventChange('event_type',e.target.value)}>{['Original Installation','Inspection','Repair','Rehabilitation','Recoat','Component Replacement','Other'].map(x=><option key={x}>{x}</option>)}</select></Field><Field label="Area"><input value={event.area} onChange={e=>eventChange('area',e.target.value)} placeholder="Floor, shell, nozzle…"/></Field><Field label="Defect / reason"><input value={event.defect_found} onChange={e=>eventChange('defect_found',e.target.value)}/></Field><Field label="Coating family"><input value={event.coating_family} onChange={e=>eventChange('coating_family',e.target.value)}/></Field><Field label="Manufacturer"><input value={event.manufacturer} onChange={e=>eventChange('manufacturer',e.target.value)}/></Field><Field label="Product used"><input value={event.product_name} onChange={e=>eventChange('product_name',e.target.value)}/></Field><Field label="Surface prep"><input value={event.surface_prep} onChange={e=>eventChange('surface_prep',e.target.value)}/></Field><Field label="DFT"><input value={event.dft} onChange={e=>eventChange('dft',e.target.value)}/></Field><Field label="Contractor"><input value={event.contractor} onChange={e=>eventChange('contractor',e.target.value)}/></Field><Field label="Source"><select value={event.source_status} onChange={e=>eventChange('source_status',e.target.value)}>{statusOptions.map(x=><option key={x}>{x}</option>)}</select></Field></div><label className="baseline-check"><input type="checkbox" checked={event.establishes_baseline} onChange={e=>eventChange('establishes_baseline',e.target.checked)}/> This work establishes a new verified coating/repair baseline</label><Field label="Notes"><textarea rows="3" value={event.notes} onChange={e=>eventChange('notes',e.target.value)}/></Field><div className="section-actions"><button className="secondary-button" onClick={()=>setAdding(false)}>Cancel</button><button className="primary-button" disabled={busy} onClick={add}>{busy?'Saving…':'Save service event'}</button></div></div>}
    <div className="dna-timeline"><h3>Coating & repair history</h3>{!events.length?<p className="muted">No documented service events yet. That is normal for a legacy asset—add history as it becomes known.</p>:events.map(item=><article key={item.id}><div className="dna-date"><strong>{formatDate(item.event_date)}</strong><small>{item.source_status}</small></div><div><strong>{item.event_type}{item.area?` · ${item.area}`:''}</strong><p>{[item.manufacturer,item.product_name||item.coating_family].filter(Boolean).join(' · ')||item.defect_found||'Service event recorded'}</p>{item.notes&&<small>{item.notes}</small>}{item.establishes_baseline&&<span className="baseline-badge">Verified baseline</span>}</div></article>)}</div>
  </section>
}
