-- PolyShield Asset IQ v2.4.3 — curated coating failure intelligence pack
-- Additive/idempotent. Installs organization-scoped expert records without overwriting customer knowledge.

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Surface rust / rust bloom','Corrosion','Orange to reddish-brown corrosion products, rust bloom, streaks or spotting on exposed steel or at coating defects.','Moisture/oxygen exposure, coating breach, inadequate protection, damaged repair edge.','Increase concern with active spread, recurrent wetting, critical location, exposed substrate or suspected pitting.','Clean representative area; close visual/probe inspection; UT where metal loss is suspected; map extent.','Correct moisture/source condition and restore compatible protective system after substrate condition is verified.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Surface rust / rust bloom'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Rust staining from seam or weld','Corrosion','Rust-colored trails emerging from welds, seams, lap joints, fasteners, coating edges or crevices.','Localized coating discontinuity, retained moisture, crevice action, weld-edge coating weakness, hidden corrosion source.','Moderate to high when staining recurs, originates from a joint, or spreads beyond a small isolated spot.','Clean origin; inspect weld/seam closely; check coating continuity/holiday where appropriate; UT if section loss is possible.','Repair depends on verified source; remove unsound coating and restore edge/seam protection.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Rust staining from seam or weld'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Under-film corrosion','Corrosion','Rust staining at coating edges, blistering with rust products, lifting film, creep from scratches/holidays, corrosion visible beneath transparent/thin areas.','Coating breach, soluble salts, poor adhesion, moisture migration, inadequate surface prep, damaged film.','High when corrosion spreads beneath apparently intact coating or causes broad loss of adhesion.','Map extent; clean/open representative failed area under approved procedure; adhesion/holiday testing as applicable; UT if metal loss suspected.','Remove failed coating to sound material, address contamination/substrate condition, restore compatible system.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Under-film corrosion'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Pitting corrosion','Corrosion','Localized cavities, pin-point depressions, crater-like attack or concentrated rust at small sites; depth cannot be judged from photo.','Localized electrochemical attack, deposits, coating holidays, stagnant chemistry, chlorides or service conditions.','High concern when numerous, deep-appearing, leaking, near welds/nozzles, or on structural/pressure-retaining areas.','Clean and measure pit depth/UT with calibrated equipment; engineering review when remaining thickness may be affected.','Repair design must be based on measured remaining thickness and service requirements.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Pitting corrosion'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Crevice corrosion indicators','Corrosion','Corrosion products concentrated at lap joints, gasket edges, bolted interfaces, clamps, deposits, supports or shielded wet areas.','Restricted oxygen/mass transfer in tight wet crevices, trapped electrolyte, deposits.','Escalate when joint integrity, fasteners, flange faces, supports or hidden section loss may be affected.','Inspect crevice after cleaning/disassembly where permitted; UT/thickness checks around affected interface.','Eliminate moisture trap where possible and repair/protect based on verified substrate condition.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Crevice corrosion indicators'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Galvanic corrosion indicators','Corrosion','Localized attack concentrated near contact between dissimilar metals, often with one metal relatively protected and adjacent metal corroding.','Electrical contact between dissimilar metals in conductive moisture/service environment.','Concern rises with rapid localized attack, wet service, small anodic area, or critical fittings.','Verify material pairing/electrical contact and service electrolyte; thickness measurement at attacked metal.','Engineering/material review may be required; isolate materials or redesign protection as appropriate.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Galvanic corrosion indicators'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Filiform-like undercoating corrosion','Corrosion','Fine thread-like or worm-like corrosion tracks progressing beneath a coating, commonly from edges or defects.','Moist humid exposure and under-film corrosion propagation; coating/substrate interface conditions.','Moderate to high when tracks are active, widespread or progressing under otherwise intact film.','Magnified close visual; map track origin/progression; assess adhesion and edge condition.','Remove affected/unsound film and correct surface preparation/environmental cause before recoating.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Filiform-like undercoating corrosion'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Microbiologically influenced corrosion indicators','Corrosion','Localized tubercles, deposits, unusual nodules, concentrated pitting beneath deposits, dark/slimy accumulations in wet systems; appearance alone is not diagnostic.','Microbial activity may contribute in suitable aqueous environments, but deposits/chemistry can look similar.','High if aggressive localized pitting is present in a compatible service environment.','Sample deposits/water when appropriate; clean and inspect beneath deposits; UT/pit depth mapping; specialist review.','Treat only after confirming mechanism; address water chemistry/biological conditions and substrate repair as needed.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Microbiologically influenced corrosion indicators'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Blistering','Coating','Raised domes, bubbles, swellings or rounded protrusions in coating/lining; may be isolated or dense.','Osmotic effects, trapped contamination/moisture, permeation, cathodic effects, application conditions, substrate corrosion.','Assess size, density, rupture, rust staining, exposed substrate and immersion/service criticality.','Document size/density; inspect representative blister under approved procedure; check for moisture/salts/corrosion beneath.','Determine cause before repair; remove failed material and restore a compatible system.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Blistering'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Osmotic blistering indicators','Coating','Multiple rounded blisters, often similar in morphology, sometimes containing liquid; may cluster in immersion areas.','Soluble salts/contamination beneath film, moisture permeation and osmotic pressure.','High when widespread, increasing, ruptured, or accompanied by under-film corrosion.','Check soluble salt history/testing where possible; inspect blister contents/substrate under approved procedure; adhesion assessment.','Do not simply overcoat; correct contamination/source and remove failed coating to sound substrate/system.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Osmotic blistering indicators'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Delamination / disbondment','Coating','Lifted, detached, tented, hollow-sounding, curled or separated coating/lining; visible separation between layers or substrate.','Adhesion loss, contamination, moisture, poor surface prep, incompatible layers, under-film corrosion.','Severity increases with broad extent, exposed substrate, immersion service or active corrosion.','Map extent; tap/probe where appropriate; inspect edges/substrate; adhesion testing when useful.','Remove unsound coating to sound edges and repair with verified compatible system.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Delamination / disbondment'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Peeling / flaking','Coating','Sheets, strips, flakes or chips separating from substrate or underlying coating.','Adhesion/cohesion failure, weathering, contamination, overcoating incompatibility, corrosion beneath.','Moderate to high when progressing, widespread or exposing substrate.','Determine failure plane; adhesion testing/edge inspection; inspect substrate for corrosion.','Remove loose/unsound layers and rebuild compatible coating system after proper preparation.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Peeling / flaking'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Cracking / checking','Coating','Linear cracks, fine checking, network cracks or fracture lines through coating; substrate may or may not be exposed.','Aging/embrittlement, excessive thickness, thermal/mechanical movement, cure/application issues, substrate movement.','High when cracks penetrate to substrate, are widening, occur at high-stress transitions or permit ingress.','Magnified close visual; determine depth/extent; inspect substrate and movement source; DFT review.','Repair cause and failed coating; flexible/detail reinforcement or engineering review may be needed at moving transitions.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Cracking / checking'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Alligatoring / mud cracking','Coating','Polygonal, reptile-skin or mud-crack pattern, often in thick/aged coating.','Excessive film build, internal stress, aging/embrittlement, incompatible layers or cure conditions.','Moderate to high if cracks are through-film, widespread or substrate is exposed.','Check DFT, adhesion and crack depth; inspect substrate beneath representative area.','Remove unstable system and recoat to approved thickness/system after cause review.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Alligatoring / mud cracking'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Pinholes / holidays','Coating','Tiny holes, voids, missed spots or exposed substrate points; may be difficult to see without close inspection.','Air entrapment, porous substrate, application technique, insufficient coverage, sharp profile peaks, damage.','High in immersion/chemical service because small discontinuities can initiate localized corrosion.','Holiday detection when appropriate for coating type/thickness; magnified visual; DFT around area.','Repair discontinuities using compatible approved procedure after confirming substrate condition.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Pinholes / holidays'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Abrasion / erosion','Coating','Thinned, polished, worn, scratched or grooved coating; directional wear, exposed substrate or feathered loss in flow/contact zones.','Mechanical contact, solids, high velocity/turbulence, cleaning, ladders/tools, repeated impact.','High when substrate is exposed or wear is rapidly progressing in critical zones.','Compare DFT to unworn areas; document wear pattern; assess service/mechanical source.','Restore coating and address wear mechanism; consider more abrasion-resistant system where specified.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Abrasion / erosion'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Impact / gouge / cut damage','Coating','Localized gouges, cuts, tears, punctures, chipped edges or impact marks with sharp boundaries.','Tool/equipment impact, dropped objects, installation damage, component contact.','Escalate when damage penetrates to substrate or occurs in immersion/chemical service.','Probe/clean damage; verify depth and substrate exposure; holiday test around repair area when appropriate.','Feather/remove damaged material and patch with compatible system following approved repair procedure.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Impact / gouge / cut damage'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Chalking / UV weathering','Coating','Powdery surface, faded/matte appearance, color loss; residue may transfer when wiped.','UV degradation and weathering, especially with susceptible resin systems.','Usually lower structural concern alone, but can indicate film erosion and loss of protective topcoat thickness.','Wipe test/visual comparison; DFT if protective film loss is a concern; inspect for cracking/erosion.','Clean and evaluate recoating/topcoat need based on remaining system integrity.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Chalking / UV weathering'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Chemical attack / softening','Coating','Swelling, softening, wrinkling, discoloration, loss of gloss, blistering, cracking or dissolution in exposed zones.','Chemical incompatibility, concentration/temperature excursion, solvent/process exposure.','High when coating loses integrity, substrate becomes exposed, or attack is rapid/localized at process contact areas.','Verify chemical, concentration, temperature and exposure history; hardness/adhesion checks as appropriate; manufacturer review.','Select repair/replacement system based on confirmed chemical service and exposure conditions.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Chemical attack / softening'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Heat / thermal degradation','Coating','Discoloration, browning, cracking, embrittlement, blistering or localized failure concentrated near heat source.','Service temperature above coating capability, thermal cycling, hot spots, steam/heat transfer conditions.','High if associated with substrate exposure, rapid progression or critical process temperature excursion.','Verify actual service/skin temperature and history; inspect DFT/adhesion; compare coating temperature rating.','Correct thermal cause and use coating system qualified for actual temperature/cycling.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Heat / thermal degradation'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Edge / weld coating breakdown','Weld / Joint','Early rusting, thin film, holidays, lifting or cracking concentrated on sharp edges, weld crowns, undercuts, attachments and geometry transitions.','Reduced film build over edges, difficult application geometry, weld defects/spatter, movement/stress concentration.','High when active corrosion is concentrated at structural welds, seams or repeated across similar details.','Close visual after cleaning; DFT around geometry; holiday testing when appropriate; UT if corrosion suggests metal loss.','Detail-prep/stripe-coat and repair per approved specification; weld repair only if engineering/weld inspection supports it.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Edge / weld coating breakdown'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Previous patch edge failure','Coating','Visible patch perimeter, color/gloss/texture change with lifting, rust staining, cracking or disbondment at repair edge.','Poor feathering/prep, incompatibility, contamination, inadequate overlap, recurring underlying cause.','Moderate to high when failure propagates around the perimeter or repeats after prior repair.','Inspect entire patch boundary; verify old/new coating compatibility and adhesion; check substrate beneath failed edge.','Remove failed repair to sound material and re-establish compatible repair with correct transition prep.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Previous patch edge failure'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Concrete cracking','Concrete','Linear or map cracks in concrete/lining; staining or leakage may track from cracks.','Shrinkage, thermal/movement stresses, structural movement, corrosion of reinforcement, chemical/physical deterioration.','High when active/wet, widening, displaced, associated with exposed reinforcement or structural movement.','Measure/map crack width and activity; moisture/leak assessment; structural/engineering review when warranted.','Repair method depends on crack cause/activity and service; do not seal active structural cracks blindly.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Concrete cracking'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Concrete spalling / delamination','Concrete','Flaking, pop-outs, hollow/detached areas, exposed aggregate or reinforcement, broken edges.','Freeze-thaw, corrosion of reinforcement, impact, chemical attack, poor bond, moisture ingress.','High when reinforcement is exposed/corroded, falling material risk exists, or section loss is significant.','Sounding survey, depth/extent mapping, inspect reinforcement, engineering review for structural areas.','Remove unsound concrete and repair substrate/reinforcement using engineered compatible repair system.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Concrete spalling / delamination'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'Efflorescence / mineral deposition','Concrete','White/gray crystalline or powdery deposits, streaks or mineral crust at cracks/joints/porous areas.','Moisture migration carrying soluble salts; leakage or seepage path.','Usually indicator rather than failure itself; concern rises when tied to active leakage, coating disbondment or concrete deterioration.','Trace moisture source; clean representative area; inspect cracks/joints and substrate moisture.','Address water path/source before cosmetic recoating or sealing.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('Efflorescence / mineral deposition'));

insert into public.failure_modes (organization_id,name,category,visual_indicators,typical_causes,severity_guidance,verification,repair_guidance)
select o.id,'FRP cracking / fiber exposure','Mechanical','Cracks, crazing, white stress marks, exposed glass fibers, resin loss, delamination or impact damage in composite laminate.','Impact, flexure, chemical attack, UV/resin degradation, manufacturing/repair defects.','High when fibers are exposed, laminate is soft/delaminated, crack penetrates thickness or service is corrosive.','Tap/visual mapping, thickness/laminate assessment, specialist composite review; inspect opposite side where accessible.','Repair laminate only using compatible engineered FRP procedure after defining damage extent.' from public.organizations o
where not exists (select 1 from public.failure_modes f where f.organization_id=o.id and lower(f.name)=lower('FRP cracking / fiber exposure'));

insert into public.inspection_standards (organization_id,name,source,version,scope,guidance,reference_url)
select o.id,'Visual coating failure recognition — AMPP reference','AMPP','Current public guidance','Protective coating inspection and failure recognition.','Use visual condition as evidence, separate observation from inferred mechanism, and verify DFT/surface preparation/adhesion or substrate condition with appropriate field methods.','https://blogs.ampp.org/protectperform/specifications-key-to-successful-coatings-projects-and-inspections' from public.organizations o
where not exists (select 1 from public.inspection_standards s where s.organization_id=o.id and lower(s.name)=lower('Visual coating failure recognition — AMPP reference'));

insert into public.inspection_standards (organization_id,name,source,version,scope,guidance,reference_url)
select o.id,'Surface preparation / adhesion — AMPP reference','AMPP','Current public guidance','Protective coatings on industrial substrates.','Poor or inadequate surface preparation can cause adhesion loss and premature coating failure. When delamination/peeling is observed, inspect the failure plane and preparation/contamination history rather than assuming one cause.','https://blogs.ampp.org/protectperform/surface-prep-standards-a-quick-summary' from public.organizations o
where not exists (select 1 from public.inspection_standards s where s.organization_id=o.id and lower(s.name)=lower('Surface preparation / adhesion — AMPP reference'));

insert into public.inspection_standards (organization_id,name,source,version,scope,guidance,reference_url)
select o.id,'Water infrastructure coating failure — Sherwin-Williams reference','Sherwin-Williams Protective & Marine','Current public guidance','Water/wastewater protective coating inspection.','Blistering, peeling, rusting and delamination are visual warning signs of coating-system deterioration. Treat these as prompts for closer field verification and substrate assessment.','https://industrial.sherwin-williams.com/na/us/en/protective-marine/media-center/articles/prevent-coating-failure-water-infrastructure.html' from public.organizations o
where not exists (select 1 from public.inspection_standards s where s.organization_id=o.id and lower(s.name)=lower('Water infrastructure coating failure — Sherwin-Williams reference'));

insert into public.inspection_standards (organization_id,name,source,version,scope,guidance,reference_url)
select o.id,'Overcoat condition screening — Tnemec reference','Tnemec','Current public guidance','Existing industrial coatings being evaluated for maintenance/overcoat.','Visually identify delamination, cracking and blistering before overcoating. Extensive unstable film should trigger adhesion/condition evaluation rather than being concealed by another coat.','https://tnemec.com/remedy-index-page/5-things-know-you-overcoat/' from public.organizations o
where not exists (select 1 from public.inspection_standards s where s.organization_id=o.id and lower(s.name)=lower('Overcoat condition screening — Tnemec reference'));

notify pgrst, 'reload schema';
